### PR TITLE
changed name of job_platform flag

### LINKED ISSUE #89: Update the job_platform name to "filter"
As with the existing `job_platform` flag we are able to fetch jobs based on the provided filter string, it would be appropriate to use the flage name as `filter` instead of `job_platform`

Update the help statement accordingly 

```
 --filter FILTER
                        Specify the filter string to fetch jobs (Example heavy build / libvirt / powervs / upgrade / 4.14 / 4.15 / 4.16 / 4.17/ 4.18 )
```

### PR DESCRIPTION
**Pull request by alokgoswami-ag**
fixes #89 
Updated the job_platform name to "filter"
``` 
PS C:\Users\AlokGoswami\project\ci-monitoring-automation> python3 .\CI_JobHistory.py --filter 4.17
1  4.16 to 4.17 upgrade
2  4.17 libvirt
3  4.17 libvirt multi
4  4.17 powervs capi
5  4.17 heavy build multi
6  4.17 heavy build
7  4.17 to 4.18 upgrade
8  4.17 MCE
9  All the above
Select the required ci's serial number with a space 9 
Enter Before date (YYYY-MM-DD): 2024-12-11
Enter After date (YYYY-MM-DD): 2024-12-11
Please select one of the option from Job History functionalities: 
1. Check Node Crash
2. Brief Job information
3. Detailed Job information
4. Failed testcases
5. Get builds with testcase failure
6. Get testcase failure frequency
Enter the option: 3
Checking runs from 2024-12-11 to 2024-12-11
--------------------------------------------------------------------------------------------------
4.17 libvirt
1 Job link: https://prow.ci.openshift.org//view/gs/test-platform-results/logs/periodic-ci-openshift-multiarch-master-nightly-4.17-ocp-e2e-ovn-remote-libvirt-ppc64le/1866645771760177152
Nightly info- registry.ci.openshift.org/ocp-ppc64le/release-ppc64le:4.17.0-0.nightly-ppc64le-2024-12-11-004258
Lease Quota- libvirt-ppc64le-0-1
No crash observed
Build Passed



1/1 deploys succeeded
1/1 e2e tests succeeded
--------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------
4.17 heavy build
1 Job link: https://prow.ci.openshift.org//view/gs/test-platform-results/logs/periodic-ci-openshift-multiarch-master-nightly-4.17-ocp-heavy-build-ovn-remote-libvirt-ppc64le/1866645771806314496
Nightly info- registry.ci.openshift.org/ocp-ppc64le/release-ppc64le:4.17.0-0.nightly-ppc64le-2024-12-11-004258
Lease Quota- libvirt-ppc64le-1-0
No crash observed
Build Passed



1/1 deploys succeeded
1/1 e2e tests succeeded
--------------------------------------------------------------------------------------------------```

### CODE REVIEW

**Review by Shilpa-Gokul — COMMENTED** [review]
/lgtm @KeerthanaAP Could you PTAL?

**Review by Shilpa-Gokul — APPROVED** [review]

**Review by KeerthanaAP — APPROVED** [review]

**Pull request merged**
