### PR TITLE
Fix(#1) Update README with new repo name

### PR DESCRIPTION
**Pull request by SurajGudaji**
Fix(#1) Update README with new repo name

### CODE REVIEW

**Review by Shilpa-Gokul — APPROVED** [review]

**Review by Shilpa-Gokul — APPROVED** [review]

**Comment by yussufsh** [comment]
lets wait for https://github.com/ppc64le-cloud/test-infra/pull/431

**Comment by Rajalakshmi-Girish** [comment]
I am facing trouble adding the webhook url.
Looking into it.

**Pull request merged**
