### PR TITLE
added 4.17 pa jobs

### PR DESCRIPTION
**Pull request by alokgoswami-ag**
1. 4.17 compact
2. 4.17 serial
3. 4.17 fips
4. 4.17 ecosystem
5. 4.17 jenkins

```
--------------------------------------------------------------------------------------------------
4.17 compact
1 Job link: https://prow.ci.openshift.org//view/gs/test-platform-results/logs/periodic-ci-openshift-multiarch-master-nightly-4.17-ocp-e2e-compact-ovn-remote-libvirt-multi-p-p/1827481192119668736
Nightly info- multi-latest-quay.io/openshift-release-dev/ocp-release-nightly@sha256:3d458dbc76b886b4748e4abc756e847015342cfbc5113854b5e72e9ee609a77d
Lease Quota- 
Node details not found
No crash observed
Unable to get cluster status please check prowCI UI



0/1 deploys succeeded
0/1 e2e tests succeeded
--------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------
4.17 fips
1 Job link: https://prow.ci.openshift.org//view/gs/test-platform-results/logs/periodic-ci-openshift-multiarch-master-nightly-4.17-ocp-fips-ovn-remote-libvirt-multi-p-p/1827466087390777344
Nightly info- multi-latest-quay.io/openshift-release-dev/ocp-release-nightly@sha256:5695dacc0cbace1fec08e695dabea53c8bb1e8707a4095dfb2496c9f68b1c8ea
Lease Quota-
No crash observed
Build Passed



1/1 deploys succeeded
1/1 e2e tests succeeded
--------------------------------------------------------------------------------------------------
4.17 serial
1 Job link: https://prow.ci.openshift.org//view/gs/test-platform-results/logs/periodic-ci-openshift-multiarch-master-nightly-4.17-ocp-e2e-serial-ovn-remote-libvirt-multi-p-p/1827450972591362048
Nightly info- multi-latest-quay.io/openshift-release-dev/ocp-release-nightly@sha256:5695dacc0cbace1fec08e695dabea53c8bb1e8707a4095dfb2496c9f68b1c8ea
Lease Quota- 
Node details not found
No crash observed
Unable to get cluster status please check prowCI UI



0/1 deploys succeeded
0/1 e2e tests succeeded
--------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------
4.17 jenkins
1 Job link: https://prow.ci.openshift.org//view/gs/test-platform-results/logs/periodic-ci-openshift-multiarch-master-nightly-4.17-ocp-jenkins-e2e-ovn-remote-libvirt-multi-p-p/1827828440103915520
Nightly info- multi-latest-quay.io/openshift-release-dev/ocp-release-nightly@sha256:cbd80dac38a81a635704963597765002707f565fe6638dfbf77122a5ec054119
Lease Quota- 
Node details not found
No crash observed
Unable to get cluster status please check prowCI UI



0/1 deploys succeeded
0/1 e2e tests succeeded
--------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------
4.17 ecosystem
1 Job link: https://prow.ci.openshift.org//view/gs/test-platform-results/logs/periodic-ci-openshift-multiarch-master-nightly-4.17-ocp-image-ecosystem-ovn-remote-libvirt-multi-p-p/1827813336192913408
Nightly info- multi-latest-quay.io/openshift-release-dev/ocp-release-nightly@sha256:b2afcdd5499a8094c17e39df02eeef96125afb91e339c3c66057a1d06d4709da
Lease Quota- 
Node details not found
No crash observed
Unable to get cluster status please check prowCI UI



0/1 deploys succeeded
0/1 e2e tests succeeded
--------------------------------------------------------------------------------------------------```

### CODE REVIEW

**Review by Shilpa-Gokul — COMMENTED** [review]
/lgtm

**Comment by alokgoswami-ag** [comment]
removed 4.11 job links

**Comment by KeerthanaAP** [comment]
@alokgoswami-ag  Can you remove this [4.17 original powervs ](https://github.com/ocp-power-automation/ci-monitoring-automation/blob/7229803cc5929bb242af1d5122d643c610f66bcd/p_periodic.json#L24) also as we have stopped it.

**Comment by KeerthanaAP** [comment]
> @alokgoswami-ag Can you remove this [4.17 original powervs ](https://github.com/ocp-power-automation/ci-monitoring-automation/blob/7229803cc5929bb242af1d5122d643c610f66bcd/p_periodic.json#L24) also as we have stopped it.

Its removed.

**Pull request merged**
